### PR TITLE
Corrected Translation

### PR DESCRIPTION
**Pull request by nschulux**
I have Updated Geode path now the Resources and Chunks are named correctly.
ein -> Ein
ein -> Aus

### CODE REVIEW

**Comment by nschulux** [comment]
Added Font Mono and Roman No9 L.
Roman Mono

**Comment by nschulux** [comment]
SymbolPS

**Comment by rabe-soft** [comment]
This font is VERY different to the original SymbolPS font. For example, the characters alphy-beta-xi will appear instead of ABX (SymbolPS). In my opinion, it is very important that the characters in the new font match those in the old font as closely as possible.
zsatz
Rainer

**Comment by nschulux** [comment]
Removed Font symbolps.ttf

**Review by bluewaysw — APPROVED** [review]

**Pull request merged**
