### PR TITLE
Add ttf fonts for test

### PR DESCRIPTION
**Pull request by jirkakunze**

### CODE REVIEW

**Comment by nschulux** [comment]
I downloaded the Fonts , good and even the Help works without SANS.FNT Font.
Start is OK quicker than with FreeFonts and they have EUROSYMBOL.
But CTL+ALT+4  can i change this to ALT GR +E on my Swiss keyboard ?
Where is the Euro on German Keyboard ?

**Comment by nschulux** [comment]
Should we not rename in 8.3 ?
PTMONOR.TTF
PTMONOI.TTF
PTSANSBI.TTF  ....

**Comment by jirkakunze** [comment]
Yes, you are right. I will correct that.

**Comment by jirkakunze** [comment]
The fonts were renamed using the following rules after the 8.3 file schema:
- Font family name 6 characters
- Style 2 characters (Re -> Regular, Bo -> Bold, It -> Italic, BI -> BoldItalic)

**Review by nschulux — APPROVED** [review]
Deutsche Hilfen von Achim werden angezeigt.
Englische Fehler KR09.

**Review by bluewaysw — APPROVED** [review]

**Pull request merged**
