### PR TITLE
Ongoing browser fixes by Marcus

### PR DESCRIPTION
**Pull request by mgroeber9110**
I have moved my browser work that is still applicable to a new branch for clarity, and will keep pushing stuff here so it can be easily tracked by others.

### CODE REVIEW

**Comment by HubertHuckevoll** [comment]
Hi Marcus, I had been working on UTF-8 as well and came pretty far... I finally died when doing form encoding, because I got lost in the DBCS compile flags. But maybe you still want to steal some code or look for places that need to be changed here: https://github.com/HubertHuckevoll/pcgeos/tree/utest.

Also, maybe we can work on the meeting (if you come...?) on the browser UI. I did a lot of work on the htmlv_ui.goh, sorting it out, separating it into more files. It would be a pity if this work was lost. Maybe we can just create a patch and put it into your branch instead of creating another branch...

What do you think? That branch is here, if you want ho have alook:
https://github.com/HubertHuckevoll/pcgeos/tree/browser-ui-multi

**Comment by mgroeber9110** [comment]
This is something where we should definitely sync up in Syhra. I did not spend a lot of effort on the UTF-8 stuff yet, just implemented a quick&dirty decoder in the HTMLgetc() code, and mostly focused on speeding up the decoding loop. This may cause a few merge conflicts with your changes that we probably can best sort out together, and maybe include Falk as well. 

Generally, I feel we should try to get the browser branches synched up more often again, so they don't diverge as much. Can you still do a diff of your branch to some base branch (e.g. [bluewaysw:149-host-tcpip-socket-driver](https://github.com/bluewaysw/pcgeos/tree/149-host-tcpip-socket-driver) so you only see your own changes? I found that this got a bit difficult with the Host TCP branch before I manually "rebased" my changes again.

**Comment by HubertHuckevoll** [comment]
Dear Marcus, as you are the far more professional developer I'd suggest that you go on with those changes and maybe get "inspired" by the one or line that I wrote and integrate it in your version of the 149er. (Or, if Falk merges parts of the 149er into the master we can create a new branch that uses etherpkt to work on peacefully...) 
    
Yes, the multi-branch is more straightforward. However, it has some experimental "code-disable" and "flag-setting-on-off" that needs to be cleaned up. Personally, I would rather just take the reworked htmlv_ui.goh and it's "child files" and integrate those in your branch. This branch also features an important bug fix that is needed when using the GEOS standard document interface (look for "a forgotten callsuper" in the commits...). 

I also cleaned up my UTF-8 branch and it is hopefully a good inspiration... like I said, I guess I was 85-90 percent done when I dropped the axe:

https://github.com/HubertHuckevoll/pcgeos/tree/utest2

Hope this helps,
Konstantin

**Comment by mgroeber9110** [comment]
After Falk's delivery of the Host IF code to master, I will close this PR and move my changes to a new branch directly from master, so they are easier to merge back later. More updates will happen on https://github.com/mgroeber9110/pcgeos/tree/browser-speedup-and-improvements after this.

**Pull request closed without merging**
