### PR TITLE
Franklin original Font.

### PR DESCRIPTION
**Pull request by nschulux**
Franklin original Font.
In previous font Ä was only ¨ !
Found by Jirka!

### CODE REVIEW

**Review by jirkakunze — APPROVED** [review]

**Comment by bluewaysw** [comment]
The goal and need here is, that, beside covering all GEOS characters, the free TTF replacement font delivers identical geometry with all needed styles.

**Comment by nschulux** [comment]
Bold and Bold Kursiv not working.

**Comment by jirkakunze** [comment]
Where can I find the other styles? Maybe the problem can be fixed easily.

**Comment by bluewaysw** [comment]
Bold and italic should be kernel applied styles, no specific style files available here.

**Review by bluewaysw — APPROVED** [review]

**Pull request merged**
