### PR TITLE
Updated Fonts PS Print

### PR DESCRIPTION
**Pull request by nschulux**
Updated Fonts PS Print works now.
image

### CODE REVIEW

**Review by nschulux — COMMENTED** [review]
Updated Fonts for Printing to PS        

Updated Fonts for Printing to PS.
Nimbus Sans works now also. **FAULTY!**
This one brings PC/geos to KR-09 :
https://github.com/bluewaysw/pcgeos/pull/614/commits/a7f4fb96c8ee1a057c91745f6fcd8b6c66224c53

**Review by nschulux — COMMENTED** [review]
These fonts make PC/GEOS run in KR-09 !

https://github.com/bluewaysw/pcgeos/pull/614/commits/a7f4fb96c8ee1a057c91745f6fcd8b6c66224c53

**Comment by jirkakunze** [comment]
I suspect something has got mixed up here.
The Nimbus ttf fonts are hosted at https://github.com/ArtifexSoftware/urw-base35-fonts. It is documented there that these fonts are under the GNU AFFERO GENERAL PUBLIC LICENSE version 3. You have provided the GNU PUBLIC LICENSE version 2 here. Is this an mistake?
I think it is not a good idea to document renames and dosnames in the license file. Maybe we can create a text file in which things like the original font name, the source of the font, the renaming under PC/GEOS, the existing styles or the mapping to the GEOS fonts is documented for all fonts we ship with the distribution.

**Comment by nschulux** [comment]
No this is not a mistake this Font is Nimbus Sans L renamed to Nimbus Sans !
The Nimbus Sans from ArtifexSoftware/urw-base35-fonts can not Print to PS afther working with FontForge the Font is very very Slow and created KR-09 ,
I am not seing if there are Kerning but they have Hinting tables.
For the License i can update the Licence by the next PR .
I see now the Bold is not always working in PS Printing but in Geowrite they are displayed correctly. 
I have checked the PS file they are differently generated.

**Comment by nschulux** [comment]
Corrected Unique Identifier for Nimbus Sans.

**Comment by nschulux** [comment]
This will close the Issue : TTF driver: printing in PS file incorrect with some fonts #603

**Comment by nschulux** [comment]
I have set this PR to Draft.

**Comment by nschulux** [comment]
Jika says to make closest to original Fonts !

**Pull request closed without merging**
